GRANT ALL ON SCHEMA mgmcrm TO postgres;
GRANT USAGE ON SCHEMA mgmcrm TO developers;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA mgmcrm TO developers;

ALTER DEFAULT PRIVILEGES IN SCHEMA mgmcrm
    GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES
    TO developers;
    
ALTER DEFAULT PRIVILEGES IN SCHEMA mgmcrm
    GRANT SELECT, UPDATE ON SEQUENCES
    TO developers;
    
ALTER DEFAULT PRIVILEGES IN SCHEMA mgmcrm
    GRANT EXECUTE ON FUNCTIONS
    TO developers;